<?php
/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_rules_category_info().
 */
function fluxtrello_rules_category_info() {
	$info =  array();
  // Use the same icon as for the service plugin.
	$info['fluxtrello'] = array(
		'label' => t('Trello')
	);
	return $info;
}

/**
 * Implements hook_fluxservice_plugin_directory().
 */
function fluxtrello_fluxservice_plugin_directory() {
	return 'lib/Drupal/fluxtrello/Plugin';
}